name: run-runner-keep-alive
on:
  workflow_dispatch:
  push:
    paths:
      - "cli.js"
      - "index.js"
      - "README.md"
      - "package.json"
      - ".github/workflows/run-runner-keep-alive.yml"
permissions:
  id-token: write # Required for OIDC
  contents: write # Thêm dòng này để có quyền push

jobs:
  run-runner-keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true # CHỈ CẦN CÁI NÀY để giữ token cho push
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: |
          node ./cli.js --interval 60 --message "Session running..."
